### ISSUE TITLE
Argument Expression Error

### ISSUE THREAD

**Issue by ghost** [andymac-2/bk22lsmv#1]
Hey, I was looking to get this tool running and I've ran into a bit of a roadblock. I've done the following:

- Installed Stack
- Did stack init/setup (didn't really do much)
- Built

When I go to run the command from my local directory:
stack exec bk22lsmv-exe ~/Desktop/lttp-eg-insanity.bk2 > ~/Desktop/lttp-eg-insanity.lsmv

I get the following error in console
bk22lsmv-exe: user error (Pattern match failure in do expression at app/Main.hs:9:3-17)

Which references this line here:
Line 9`  (bk2: lsmv : _) <- getArgs`

Since Haskell is a tad foreign to me outside of my usual C-style languages, I can only guess that it doesn't like the argument pattern. 

Attached is a copy of my stack install as well as the build.
[bk22lsmv-build.txt](https://github.com/andymac-2/bk22lsmv/files/2753840/bk22lsmv-build.txt)
[stack-build-log.txt](https://github.com/andymac-2/bk22lsmv/files/2753842/stack-build-log.txt)

System Specs:
Linux Mint 19.1 Tessa, XFCE (Ubuntu Bionic 18.04, x64)
Kernel 4.15.0-43-generic

Let me know if I'm just overlooking something stupid here. Would be cool to use this tool. Thanks.

**Comment by ghost** [comment]
Never mind I figured out what I needed to to. Thanks. :)

**Comment by andymac-2** [comment]
Hi, can you tell me how you fixed it? I'll put a better error description in if you like. I'm guessing you only used one argument instead of two?

**Comment by ghost** [comment]
It's because the command requires an already existing lsmv to patch, which, if I would have just read more carefully (both in the readme and code), would have made sense.

I was doing:
bk2 > lsmv

Instead of:
bk2 existing_lsmv > new_lsmv

It would be nice if the tool didn't require an lsmv to patch on top of but I don't know the limitation of that sort of implementation.  In regards to an error, I would make it something simple as:

Invalid command. Usage: file.bk2 file.lsmv > new_file.lsmv

Or something like that. Thanks for following up!
